### ISSUE TITLE
Having issues with default_actions

### ISSUE THREAD

**Issue by dexterlakin** [terraform-aws-modules/terraform-aws-alb#175]
default_action = {
        action_type = "fixed-response"
        fixed_response = {
          content_type = "text/plain"
          message_body = "OK"
          status_code  = "200"
        }
      }
      
 Is there something wrong with this configuration? It appears to always plan a "forward" response.
 
 Does anyone have a working example or is this a bug?

**Comment by bmurphey** [comment]
I was bumping into this issue as well.  I believe what's needed is to remove the `default_action` wrapping map.  I got the same `default_action` idea from looking at the dynamic `default_action` block code.  However, it appears the issue is that since the code isn't using a custom `iterator` argument for the dynamic block, it "defaults to the label of the dynamic block" per TF documentation; in this case `default_action`.  Thinking about it some more, when configuring the listeners, the only available "action" option is the default action.  Any other actions are configured in the listener rules.  Since removing the `default_action` wrapper, my plans have output what I would expect.

**Comment by wiegandf** [comment]
It is working like this: 
```
  https_listeners = [
    {
      ...
      action_type = "fixed-response"
      fixed_response = {
        status_code  = "401"
        content_type = "text/plain"
      }
      ...
    }
  ]

**Comment by vojtapol** [comment]
@wiegandf that worked

Could anyone please explain to me how would I find out how to do this using the documentation?

Here is the description for the `https_listener` field:

> A list of maps describing the HTTPS listeners for this ALB. Required key/values: port, certificate_arn. Optional key/values: ssl_policy (defaults to ELBSecurityPolicy-2016-08), target_group_index (defaults to https_listeners[count.index])

Absolute no mention of `fixed_response` or anything of that sort.

**Comment by jonathanhle** [comment]
> It is working like this:
> 
> ```
>   https_listeners = [
>     {
>       ...
>       action_type = "fixed-response"
>       fixed_response = {
>         status_code  = "401"
>         content_type = "text/plain"
>       }
>       ...
>     }
>   ]
> ```

Saved me a bunch of hours totally worked.  Indeed, docs not great here.  Here's my complete example below:
```
  https_listeners = [
    {
      port            = 443
      protocol        = "HTTPS"
      ssl_policy      = var.ssl_security_policy
      certificate_arn = data.aws_acm_certificate.alb_tls.arn

      # Listener Default Action
      action_type = "fixed-response"
      fixed_response = {
        status_code  = "401"
        content_type = "text/plain"
        message_body = "OK"
      }
    }
  ]
```
