### ISSUE TITLE
can't create http listener rules

### ISSUE THREAD

**Issue by michaelkoro** [terraform-aws-modules/terraform-aws-alb#176]
Hi, i noticed there is no support for creating http listener rules (only https rules supported according to https://github.com/terraform-aws-modules/terraform-aws-alb/pull/155).
Is there a fix available?
Thanks.

**Comment by METAJIJI** [comment]
May be this useful?
https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/examples/complete-alb/main.tf#L100

**Comment by antonbabenko** [comment]
As @METAJIJI just pointed out, you should set `http_tcp_listeners`. See examples for more details.

**Comment by Binternet** [comment]
@antonbabenko not sure I'm getting you.
Can you please show a small example?

**Comment by antonbabenko** [comment]
Sorry, I don't have time for this. Please check the code in the examples folder - they are a good starting point.

**Comment by sjethvani** [comment]
Ask for this issue was to add a support of 'adding **listener** **rules** for **http** listener' & not the **http listener itself** 

If you check this , https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/examples/complete-alb/main.tf you will see that it has only **https_listener_rules** support , it is missing **http_listener_rules**.
