### ISSUE TITLE
Missing NLB Example using Instance target ID's

### ISSUE THREAD

**Issue by jsaustinhell** [terraform-aws-modules/terraform-aws-alb#218]
This is a question rather than a bug.

I cannot see a way of using Target ID's of an EC2 instance in the aws_lb_target_group_attachment Resource.

I presume the ID's need to be added to the var.target_groups somehow. Could an example of this be added?

**Comment by rmasclef** [comment]
Hi, you might have an answer looking at the PR : https://github.com/terraform-aws-modules/terraform-aws-alb/pull/191

But it doesn't really show how to define multiple targets (eg: using a `for` on instance-ids into the `target` entry

**Comment by antonbabenko** [comment]
Thanks @rmasclef for linking to #191.

You can look into `complete-alb` example for this. `targets` should be defined in `target_groups` and it is up to the developer to figure out how to create that map with targets (using `for` loops or any other way).

https://github.com/terraform-aws-modules/terraform-aws-alb/blob/eac30ff6ce9897a338ab3e5a2b186976594c7ab2/examples/complete-alb/main.tf#L328-L337

Closing this one, because `complete-alb` example should answer the question.

**Comment by rmasclef** [comment]
If think the issue was more explaining that the **N**LB example were missing, closing this one without adding an example in the NLB part might finish with other users (that are not really rigorous to take time to look at the existing closed issues ...) opening the same kind of issues 😬.

---

Just a quick note on that ALB example, what can be done if the user creates multiple ec2 instances ?

```
# create multiple EC2 instances
resource aws_instance "my_instances" {
    count = var.nb_desired_instances
    ...
}

# create one LB with one target-group having all the created EC2 ids as targets
module "alb" {
  source = "../../"

  [...]

  target_groups = [
    {
      ...
      target_type          = "instance"
      health_check = {
         ...
      }
      targets = {
        my_ec2 = {
          target_id = aws_instance.this.id
          port      = 80
        },
        # how can we for each on `aws_instance.my_instances.*` to define them as target ?
      }
    }
}
```

For example, technically, at this time, I'm not using the `target` property and I define an `aws_target_group_attachment` which works but, I'm pretty sure there's a better way to do it using the entire module capabilities.

Maybe my specific usage is wrong (i.e I mean ... Why am I not using ECS to do this ? 🤷‍♂️)

**Comment by antonbabenko** [comment]
Suggestions and PRs where examples or documentation is improved without repeating more trustful sources (eg, Terraform docs - to learn how Terraform `for` loops work, AWS docs - to learn how certain features or services work on AWS) is very welcome.

Answering your question about how to make `targets` from resources (see official docs for detailed explanation):

```hcl
  targets = {
    for k, v in aws_instance.my_instances:
      k = {
        target_id = v.id
        port      = 80
      }
  }
```
