### ISSUE TITLE
enable_waf_fail_open. set to FAIL with new terraform.

### ISSUE THREAD

**Issue by hatan4ik** [terraform-aws-modules/terraform-aws-alb#230]
Since upgrade to terraform 1.1.1  its trying to revert back to default "false":

      ~ enable_waf_fail_open       = true -> false

Adding "enable_waf_fail_open" not implemented in the module and througt following error:

Error: Unsupported argument
│ 
│   on elb_external_app-lb.tf line 186, in module "alb-ext-app":
│  186:   enable_waf_fail_open       = true
│ 
│ An argument named "enable_waf_fail_open" is not expected here.

Please fix.

**Comment by wwwizards** [comment]
@hatan4ik  - I had a similar error which turned out to be a [bug in the aws provider. 
that was fixed with v3.69](https://github.com/hashicorp/terraform-provider-aws/issues/22037) - however, for this it also looks like there is a breaking-change in the  syntax for aws_lb_listener_rules - this has changed along with the updated provider. I suspect this project will need to be forked for newer tf versions moving forward.
