### ISSUE TITLE
How to remove initial tag

### ISSUE THREAD

**Issue by globart** [terraform-aws-modules/terraform-aws-alb#337]
Can terraform-aws-modules = "alb" tag be removed somehow? I don't want it added to my LB resources

**Comment by antonbabenko** [comment]
It is being added in the example only. You can edit the code as you need. For e.g., here - https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/examples/complete-alb/main.tf#L17

**Comment by globart** [comment]
@antonbabenko I'm trying to add my own tags, but they don't override the default one, you've written into the module itself - https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/main.tf#L5C38-L5C38

**Comment by bryantbiggs** [comment]
this tag is used to link this project back to resources created within AWS. in order for AWS to understand why this project, and others within the `terraform-aws-modules`, are important and worth investing time/resources into them, there needs to be a way for AWS to understand the impact (i.e. - revenue) generated by these projects. In hindsight, this tag doesn't need to be on every resource created - we could move it to just the load balancer itself. however, I would strongly prefer to keep this tag and continue adding it to the projects so that we have a way to show impact in a way that AWS understands (GitHub stars, Terraform registry downloads, etc. are not indicative but its what has been used to try to make the case, in addition to anecdotal statement from users). Thoughts?

**Comment by globart** [comment]
@bryantbiggs In that case, I think you should atleast add some flag/option to disable it, so people have the option to have their resources fully untagged or only with their own tags. So by default this new flag/option will be set such that this tag will be added, but it can be changed so it is not, in my opinion, this is the best solution for everyone

**Comment by bryantbiggs** [comment]
> this is the best solution for everyone
I would argue the best solution for everyone is to have it so we have the data that shows AWS that they should continue investing time/resources into these projects, no? Feels like an easy compromise for something that is provided for free to users. Again, we can reduce the amount of tags here to just the LB so we're only talking about one tag on one resource in this module

**Comment by globart** [comment]
@bryantbiggs Well, you know better what will be best, as you are maintainer and I'm just a user 😄 , but reducing the number of tags so they are only applied to the resources, which actually contribute to the costs, can make it better than how it is now. Just of curiosity, how is AWS involved in these modules, if they are maintained by non-AWS people? Do they provide some fundind or atleast priority issues support to the maintainers?

**Comment by bryantbiggs** [comment]
> Just of curiosity, how is AWS involved in these modules, if they are maintained by non-AWS people? Do they provide some fundind or atleast priority issues support to the maintainers?

Thats complicated to answer so I will only speak for myself. I am currently an AWS employee, and every year I have to account for where I spend my time and its been challenging to relate the time/effort spent on these modules and what AWS gets in return for that. There are a number of OSS projects that AWS sponsors all the time, but before they will provide funding, they need to see data that supports funding those projects (funding can be direct monetary contributions or allocating headcount to work on those projects or funding individuals who work/contribute to those projects, etc. There are many various forms)

**Comment by globart** [comment]
Got it, in this case reducing the number of tags is a good compromise, in my opinion. @antonbabenko what do you think?
