### ISSUE TITLE
load_balancer_name length restriction?

### ISSUE THREAD

**Issue by halfshellhero** [terraform-aws-modules/terraform-aws-alb#52]
I'm trying to understand what the logic was behind restricting the load_balancer_name length per:

https://github.com/terraform-aws-modules/terraform-aws-alb/blob/dea191d9b15b7af4b66418b6504a03f0b0b9af24/main.tf#L1-L4

The AWS docs indicate a max length of 32 characters, so why limit that further?
Ref: https://docs.aws.amazon.com/elasticloadbalancing/2012-06-01/APIReference/API_CreateLoadBalancer.html

**Comment by halfshellhero** [comment]
So, I was directed to this which I currently understand to be related or causing this.

https://github.com/terraform-providers/terraform-provider-aws/issues/625

Would still like to confirm if there is any other way to approach this aside from having a non-descriptive resource name.

**Comment by michaelmoussa** [comment]
+1

Due to how the Terraform `aws_lb` resource works, there doesn't appear to be any way to explicitly name ALBs using the `terraform-aws-alb` module now:

https://github.com/terraform-aws-modules/terraform-aws-alb/blob/dea191d9b15b7af4b66418b6504a03f0b0b9af24/main.tf#L8

`name_prefix` and `name` are not compatible with each other; neither will override the other - it will just error out with `Error: aws_lb.application: "name": conflicts with name_prefix`.

Based on the CHANGELOG for v3.0.0 (_"`name_prefix` used where possible to avoid naming conflicts in resource testing."_), it seems this was primarily done to facilitate testing rather than out of any specific user request. As an alternative, what about restoring the previous `name            = "${var.alb_name}"` behavior and simply appending a [random_id](https://www.terraform.io/docs/providers/random/r/id.html) to the `${var.alb_name}` that the resource tests pass to the module?

That should address naming conflicts when testing while not forcing consumers to limit the resource name's descriptiveness to a mere 6 characters.

**Comment by brandoconnor** [comment]
Hey @michaelmoussa  and @halfshellhero -

It's hard to know what consensus is around using either `name` or `name_prefix`. Generally, when trying to find a resource I think it's a better practice to avoid relying on the resource name which is an **inconsistent construct in AWS** (sometimes aligns with the `Name` tag, other times it's essentially an ID since it requires uniqueness). Tags on the other hand are largely a consistent concept and I'd rather rely on a collection of tags (sometimes including `Name`) for finding resources as these provide a way to slice and dice on several dimensions. It's a practice I'd like to promote as much as possible but I can see how some people/organizations with hard and fast rules about resource naming would not necessarily agree.

The benefit of altogether avoiding name conflicts is somewhat marginal in the testing realm here. I rarely create more than one alb for test within the same region at any given time though the conflict has come up when CI runs and I'm working locally in the same region. I can see how it'd be somewhat disruptive for those trying to upgrade and use the newer version of the module - that's why new major version was created. It's not a trivial thing for a maintainer to balance! 😄 

Does that all make sense? Have I persuaded anyone? I'm happy to solicit more opinion and if more than a folks think preserving the resource name as a flexible thing is worthwhile, I'll take the PR.

**Comment by brandoconnor** [comment]
@halfshellhero - Yea, you found the relevant issue. I hadn't looked deeper but the 6 character limit seemed to be due to the 26 character suffix that terraform appends to at least this resource.

**Comment by brandoconnor** [comment]
Mehh I'm more invested in moving the project forward than waiting for an unknown userbase to chime in. Taking the PR and moving forward.

**Comment by michaelmoussa** [comment]
@brandoconnor I can understand the motivation, especially if someone is managing an environment exclusively via automation and leaving it up to the tools to identify resources.

Ultimately though, I think it comes down to principle of least surprise. Passing `my-load-balancer` as the value for the `load_balancer_name` parameter and ending up with a load balancer called `my-load-balancer` is not surprising at all, while ending up with `my-loa##########################` would definitely prompt a "what the!?!?!" reaction. :)

Thanks for the merge!

**Comment by halfshellhero** [comment]
:+1: thanks @brandoconnor!
