### ISSUE TITLE
Create multiple target groups from different folders

### ISSUE THREAD

**Issue by 0rc** [terraform-aws-modules/terraform-aws-alb#55]
Scenario:
Given we have plenty of microservices, it's not cost effective to create alb per each service
Suggested:
Split to two modules: one for alb itself and one for registering microservice with alb

**Comment by brandoconnor** [comment]
Hey @0rc - 

I missed this issue as it rolled in. I've since made some changes to the module that allow listeners and target groups to be attached as flexible lists of maps that describe each resource. I think that would cover your use case here. Fill me in if you had something else in mind... that's all I can imagine you're asking about. Be as specific as you can... Just asking for a module for registering microservices doesn't really describe the resources that would be involved.
