### ISSUE TITLE
How to modify default action (I'd like to redirect http to https)

### ISSUE THREAD

**Issue by thalesac** [terraform-aws-modules/terraform-aws-alb#82]
**Is your feature request related to a problem? Please describe.**
I'm trying to redirect http to https but I can't see any option in the documentation

**Describe the solution you'd like**
Set those somewhere: https://www.terraform.io/docs/providers/aws/r/lb_listener.html#redirect-action

**Describe alternatives you've considered**
Manually changing the ALB after creation

**Comment by ChrisLopezUK** [comment]
+1 on this.

Would be really useful.

**Comment by Ashtonian** [comment]
also, fixed response defaults, which I think are finally here https://aws.amazon.com/about-aws/whats-new/2018/07/elastic-load-balancing-announces-support-for-redirects-and-fixed-responses-for-application-load-balancer/ 

It would be really nice to set up the LB to be able to redirect to https and have a default 404.

**Comment by colindean** [comment]
https://github.com/terraform-aws-modules/terraform-aws-alb/pull/78 would solve this.

**Comment by okonon** [comment]
It would be awesome if @alkalinecoffee can merge above PR

**Comment by alkalinecoffee** [comment]
I’m not a maintainer of this repo. Sorry, can’t help you here.

**Comment by antonbabenko** [comment]
Hi all,

Forgot to mention that all types of ALB listener actions (redirect, fixed-response, authenticate-cognito, authenticate-oidc) are supported since [v5.3.0](https://github.com/terraform-aws-modules/terraform-aws-alb/releases/v5.3.0) of this module.

Check out code in [examples/complete-alb](https://github.com/terraform-aws-modules/terraform-aws-alb/tree/master/examples/complete-alb) for more details.

Closing this issue/pr.
